version: '3.8'

services:
  inventory-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      HOST: 0.0.0.0
      PORT: 5000
      DEBUG: "false"
      DB_PATH: /app/data/app.db
    volumes:
      - app-data:/app/data
    networks:
      - infini-net

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - infini-net

volumes:
  app-data:

networks:
  infini-net:
    driver: bridge

